# 用于在 GitHub 仓库发布新版本时，自动将应用程序
# 发布到 WinGet（Windows 包管理器）中
# WinGet 类似于 Linux 系统中的 apt，默认使用微软官方的软件源,
name: Publish to WinGet
on:
  # 指定触发事件为 GitHub 仓库的发布（Release）事件
  release:
    # 触发条件为“发布新版本”（released）
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
        # 一个专门用于将应用程序发布到 WinGet 的工具
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          # 指定应用程序在 WinGet 中的唯一标识符
          identifier: RustDesk.RustDesk
          version: ${{ github.event.release.tag_name }}
          # 提供一个 GitHub Secret，用于认证和授权发布到 WinGet
          token: ${{ secrets.WINGET_TOKEN }}
